# Generated by Django 6.0.3 on 2026-03-24 22:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('ideology', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#1a56db', max_length=7)),
                ('logo_emoji', models.CharField(default='🗳️', max_length=10)),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('national_id', models.CharField(blank=True, max_length=13, verbose_name='เลขบัตรประชาชน')),
                ('district', models.CharField(default='เขต 1', max_length=100, verbose_name='เขตเลือกตั้ง')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('candidate_number', models.PositiveIntegerField()),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.party')),
            ],
            options={
                'ordering': ['candidate_number'],
                'unique_together': {('district', 'candidate_number')},
            },
        ),
        migrations.CreateModel(
            name='VoteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('constituency', 'ส.ส. เขต'), ('party', 'พรรคการเมือง')], max_length=20)),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('citizen', 'vote_type')},
            },
        ),
    ]
